"""Atualiza modelos

Revision ID: c429920cb833
Revises: 
Create Date: 2025-09-05 22:32:12.355918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c429920cb833'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('quantidade_minima', sa.Float(), nullable=False),
    sa.Column('quantidade_total', sa.Float(), nullable=True),
    sa.Column('notificado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('relatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cliente', sa.String(length=100), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('tarefa', sa.String(length=150), nullable=False),
    sa.Column('materiais_gastos', sa.JSON(), nullable=True),
    sa.Column('metros_quadrados', sa.Float(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('papel', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_atual', sa.Float(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    op.drop_table('usuario')
    op.drop_table('unidade')
    op.drop_table('relatorio')
    op.drop_table('categorias')
    # ### end Alembic commands ###
